In [1]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A)


[[1 2 3]
 [4 5 6]]


In [2]:
# sum

B = np.array([[7, 8, 9],
              [10, 11, 12]])

print("A + B =")
print(A + B)


A + B =
[[ 8 10 12]
 [14 16 18]]


In [4]:
# scalar multiplication

print("2 * A =")
print(2 * A)


2 * A =
[[ 2  4  6]
 [ 8 10 12]]


In [6]:
# multiplication

C = np.array([[1, 0],
              [0, 1],
              [1, -1]])

print("A * C =")
print(np.dot(A, C))


A * C =
[[ 4 -1]
 [10 -1]]


In [7]:
I = np.eye(2)
print("Macierz jednostkowa:")
print(I)


Macierz jednostkowa:
[[1. 0.]
 [0. 1.]]


In [8]:
print("A transponowana:")
print(A.T)


A transponowana:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
ket1 = np.array([[1/np.sqrt(2)],
                 [1/np.sqrt(2)]])

bra1 = np.conj(ket1.T)

print("Iloczyn ⟨ψ|ψ⟩:")
print(np.dot(bra1, ket1))  # result = [[1.]]
